### ISSUE TITLE
Problem with UTF-8 passwords

### ISSUE THREAD

**Issue by MotovilovIvan** [bwalding/ruby-drupal-hash#1]
Hello, I'm use code from this module to create custom authentication for Redmine to look in Drupal database for login/password check.
An it work fine with passwords [a-z0-9] but with UTF-8 russian symbols in password redmine have following error:
```ruby
Encoding::CompatibilityError (incompatible character encodings: ASCII-8BIT and UTF-8):
  app/models/auth_source_a.rb:152:in `block in verify'
  app/models/auth_source_a.rb:151:in `upto'
  app/models/auth_source_a.rb:151:in `verify'
```
Piece of that file is:
```ruby
    count_log2 = ITOA64.index(setting[3])
    
    if count_log2 < DRUPAL_MIN_HASH_COUNT or count_log2 > DRUPAL_MAX_HASH_COUNT
      return false
    end

    salt = setting[4..4+7]
    
    if salt.length != 8
      return false
    end
    
    count = 2 ** count_log2
       
    pass_hash = HASH.digest(salt + password)

    1.upto(count) do |i|
      pass_hash = HASH.digest(pass_hash + password)
    end

    hash_length = pass_hash.length
```
Erorr raise in that upto block
```ruby
    1.upto(count) do |i|
      pass_hash = HASH.digest(pass_hash + password)
    end
```
Next piece of code for getting hash of password from database:
```ruby
      passHash = db.select_one("SELECT pass FROM users WHERE #{self.attr_login} = '#{db.quote_string(login)}'")
      if verify(password, passHash['pass'])
      resultRow = db.select_one(
        "SELECT #{self.attr_login}, #{self.attr_mail} FROM users WHERE #{self.attr_login} = '#{db.quote_string(login)}'")
      unless(resultRow.nil? or resultRow.empty?)
...
```
I am do not have any expirience in Ruby but have an opinion that hash from database in binary format and password from Redmine login form in utf-8. How i can resolve this?
Drupal works fine with utf-8 passwords.
Redmine set to work with utf-8

**Comment by MotovilovIvan** [comment]
Fix problem with following code:
```ruby
    1.upto(count) do |i|
      pass_hash = HASH.digest(pass_hash.force_encoding(Encoding::UTF_8) + password)
    end
```
